"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./Providers";
import Header from "@/components/Header";
import { Toaster } from "@/components/Toaster";

import "@controle-devs-ui/react/dist/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Controle de Devs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
